app:
  port: 5000
  page_size: 5
  token_secret: "I_Love_LiteRank"
  token_hours: 24
db:
  file_name: "test.db"
  host: mysql
  port: 3306
  user: "test_user"
  password: "test_pass"
  database: "lr_book"
  mongo_uri: "mongodb://mongo:27017"
  mongo_db_name: "lr_book"
cache:
  host: redis 
  port: 6379
  password: "test_pass"
  db: 0
